name = "kutsenko-homepage"
main = "index.js"
compatibility_date = "2025-11-15"

kv_namespaces = [
  { binding = "HOMEPAGE_CACHE", id = "004be986ba2e4f96ac65290ccb57c196" }
]

[[triggers]]
crons = ["0 * * * *"]
